#!/usr/bin/env python3
"""
Offline pseudo-label fine-tuning for DiffusionSnake FM denoiser.

Unlike online distillation (V5b/V6/V7), this script:
  1. Uses PRE-GENERATED best-of-k displacements (fixed offline targets)
  2. Allows much higher learning rate (no moving-target instability)
  3. Trains only the FM denoiser weights (frozen CNN backbone)

The pseudo-labels are generated by scripts/gen_train_pseudo_labels.py.

Usage:
    CUDA_VISIBLE_DEVICES=4 CFG_FILE=configs/btcv_v3_4_fm_rl_v5b_gpu4.yaml \
    PSEUDO=data/pseudo_labels/btcv_train_k8.json \
    CKPT=data/outputs/btcv_diffusion_dit_v3_4_fm_full_noleak_yolom_gpu35_reusemax/checkpoints/latest.pt \
    LR=1e-5 STEPS=200 BATCH_SIZE=4 \
    SAVE_DIR=data/outputs/btcv_fm_pl_finetune_k8_lr1e5 \
        python scripts/finetune_with_pseudo_labels.py
"""

import os, sys, json, datetime, random
import numpy as np
import torch
import torch.nn.functional as F

_THIS_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _THIS_DIR)

_DEFAULT_CFG = os.path.join(_THIS_DIR, 'configs', 'btcv_v3_4_fm_rl_v5b_gpu4.yaml')
if not os.environ.get('CFG_FILE'):
    os.environ['CFG_FILE'] = _DEFAULT_CFG

from lib.config import cfg
from lib.datasets.collate_batch import make_collator
from lib.datasets.make_dataset import make_dataset
from lib.datasets.transforms import make_transforms
from lib.networks import make_network
from lib.train.trainers import make_trainer
from lib.utils.snake import snake_config, snake_gcn_utils
import torch.nn.functional as F


# ─── model loading ────────────────────────────────────────────────────────────

def load_model(ckpt_path):
    """Load the network and return (model, device)."""
    network = make_network(cfg)
    trainer = make_trainer(cfg, network)
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    if not os.path.exists(ckpt_path):
        raise FileNotFoundError(f'Checkpoint not found: {ckpt_path}')

    ckpt_obj = torch.load(ckpt_path, map_location='cpu')
    sd = ckpt_obj.get('state_dict') or ckpt_obj.get('model') or ckpt_obj.get('net') or ckpt_obj
    from lib.networks.diffusion.pretrain_evolution import remap_legacy_state_dict
    sd = remap_legacy_state_dict(sd)

    wrapper = trainer.network.module if hasattr(trainer.network, 'module') else trainer.network
    info = wrapper.load_state_dict(sd, strict=False)
    print(f'[✔] Loaded {len(sd) - len(info.missing_keys)}/{len(sd)} keys')
    return trainer.network.to(device), device


def save_checkpoint(model, step, save_dir):
    """Save checkpoint in grpo_train_v2-compatible format (net.* key prefix)."""
    os.makedirs(os.path.join(save_dir, 'checkpoints'), exist_ok=True)
    # trainer.network (or its .module) holds state_dict with 'net.*' prefix
    # — same layout the original training and eval scripts expect.
    wrapper = model.module if hasattr(model, 'module') else model
    sd = wrapper.state_dict()
    ckpt = {'state_dict': sd, 'step': step}
    path = os.path.join(save_dir, 'checkpoints', f'step{step:03d}.pt')
    torch.save(ckpt, path)
    torch.save(ckpt, os.path.join(save_dir, 'checkpoints', 'latest.pt'))
    return path


# ─── per-batch fine-tuning step ───────────────────────────────────────────────

def finetune_step(model, device, batch, pl_entry, optimizer, grad_clip=0.5, iter_steps=3,
                  anchor_weights=None, anchor_lambda=0.0):
    """
    One FM fine-tuning step using offline pseudo-label targets.

    Samples frac ∈ {0, 1/iter_steps, ..., (iter_steps-1)/iter_steps} to match the
    original iterative-refinement training distribution (V4.4 code path).  This is
    critical: training only at frac=0 breaks the model's ability to refine at fracs
    1/3 and 2/3, causing catastrophic regression after iterative inference.

    Args:
      pl_entry:    single pseudo-label entry for this batch (pre-looked-up)
      iter_steps:  number of refinement iterations (default 3, matching config)
    Returns:
      loss_val (float), grad_norm (float)
    """
    for key, val in batch.items():
        if isinstance(val, torch.Tensor):
            batch[key] = val.to(device)

    core = model.net if hasattr(model, 'net') else model
    gcn = core.gcn

    # ----- CNN features (frozen — eval mode) -----
    model.eval()  # freeze BN/Dropout in CNN backbone
    with torch.no_grad():
        yolo_out = core.yolo(batch['inp'])
        feat_list = yolo_out[1] if isinstance(yolo_out, (list, tuple)) and len(yolo_out) > 1 else None
        feat_p2 = feat_list[0] if isinstance(feat_list, (list, tuple)) else yolo_out
        cnn_feature = core.cnn_proj(feat_p2)
        if getattr(core, 'use_p3_features', False) and hasattr(core, 'cnn_proj_p3'):
            if isinstance(feat_list, (list, tuple)) and len(feat_list) > 1:
                feat_p3 = feat_list[1]
                feat_p3_up = F.interpolate(feat_p3, size=feat_p2.shape[-2:],
                                            mode='bilinear', align_corners=False)
                cnn_feature = cnn_feature + core.cnn_proj_p3(feat_p3_up)
        cnn_feature = cnn_feature.detach()

    # Put denoiser in train mode (enables Dropout regularization if present)
    gcn.train()

    # ----- Initial polygon -----
    i_init = batch['i_it_py'].view(-1, batch['i_it_py'].shape[-2], 2).detach()
    py_ind = torch.zeros(i_init.size(0), dtype=torch.long, device=device)

    # ----- Load pseudo-label displacement -----
    disp_np = np.array(pl_entry['best_disp'], dtype=np.float32)  # [N_contours, 128, 2]
    pl_disp_raw = torch.from_numpy(disp_np).to(device)

    # Align n_contours (in case of mismatch from collation)
    n = min(i_init.size(0), pl_disp_raw.size(0))
    if n == 0:
        return None, None
    i_init_n = i_init[:n].float()
    py_ind_n = py_ind[:n]
    cnn_feat_n = cnn_feature  # shape unchanged for single image
    pl_disp_n = pl_disp_raw[:n].float()  # full displacement from i_init → GT (pixel space)

    # ----- Multi-frac training: mirror the original iterative-refinement distribution -----
    # Sample frac ∈ {0, 1/iter_steps, ..., (iter_steps-1)/iter_steps} per contour.
    # frac > 0 simulates starting mid-way through the refinement chain, forcing the
    # denoiser to learn good velocities for ALL iteration positions, not just frac=0.
    if iter_steps > 1:
        situations = torch.randint(0, iter_steps, (n,), device=device)
        frac = situations.float().view(n, 1, 1) / float(iter_steps)
    else:
        frac = torch.zeros(n, 1, 1, device=device, dtype=pl_disp_n.dtype)

    # Shift starting polygon to the frac-interpolated position along total displacement
    i_init_adj = i_init_n + pl_disp_n * frac          # [N, 128, 2]
    c_init_adj = snake_gcn_utils.img_poly_to_can_poly(i_init_adj)

    # Remaining displacement from the adjusted starting position to GT
    pl_disp_remaining = pl_disp_n * (1.0 - frac)      # [N, 128, 2]

    # ----- FM training step (using adjusted polygon) -----
    # Compute features and scale from the adjusted starting polygon
    with torch.no_grad():
        distill_ctx = gcn.prepare_sampling_context(cnn_feat_n, i_init_adj, py_ind_n)

    contour_scale = distill_ctx['contour_scale'].detach()  # (N, 1, 1)
    x1 = gcn.normalize_target_disp(pl_disp_remaining, contour_scale).detach()
    t = gcn.sample_train_t(n, device=device, dtype=x1.dtype)
    x0 = gcn.sample_train_x0(x1).detach()
    x_t = (1.0 - t) * x0 + t * x1
    v_target = (x1 - x0).detach()

    contour_scale_flat = contour_scale.view(-1).to(dtype=x1.dtype)

    # Only denoiser trains; backbone is frozen
    v_pred, l_reg = gcn.predict_velocity(
        cnn_feat_n,
        i_init_adj,
        c_init_adj,
        distill_ctx['sampled_feat'],
        distill_ctx['detail_feat'],
        py_ind_n,
        x_t,
        t.view(-1),
        contour_scale=contour_scale_flat,
        x_self_cond=None,
    )

    loss = F.mse_loss(v_pred, v_target, reduction='mean')
    if isinstance(l_reg, torch.Tensor):
        loss = loss + l_reg.mean() * 0.0  # keep l_reg hooks alive but zeroed

    # Anchor regularization: L2 penalty toward baseline weights (prevents catastrophic forgetting)
    if anchor_weights is not None and anchor_lambda > 0:
        anchor_loss = sum(
            (p - anchor_weights[name].to(p.device)).pow(2).mean()
            for name, p in model.named_parameters()
            if p.requires_grad and name in anchor_weights
        )
        loss = loss + anchor_lambda * anchor_loss

    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    grad_norm = torch.nn.utils.clip_grad_norm_(
        [p for p in model.parameters() if p.requires_grad],
        max_norm=grad_clip,
    )
    optimizer.step()

    return float(loss.item()), float(grad_norm.item() if hasattr(grad_norm, 'item') else float(grad_norm))


# ─── main ─────────────────────────────────────────────────────────────────────

def main():
    pseudo_rel = os.environ.get('PSEUDO', 'data/pseudo_labels/btcv_train_k8.json')
    ckpt_rel = os.environ.get('CKPT',
        'data/outputs/btcv_diffusion_dit_v3_4_fm_full_noleak_yolom_gpu35_reusemax/checkpoints/latest.pt')
    lr = float(os.environ.get('LR', '1e-5'))
    steps = int(os.environ.get('STEPS', '200'))
    batch_size = int(os.environ.get('BATCH_SIZE', '4'))
    save_every = int(os.environ.get('SAVE_EVERY', '20'))
    grad_clip = float(os.environ.get('GRAD_CLIP', '0.5'))
    iter_steps = int(os.environ.get('ITER_STEPS', '3'))  # must match config iterative_num_steps
    gain_threshold = float(os.environ.get('GAIN_THRESHOLD', '0.0'))  # filter by pseudo-label gain
    anchor_lambda = float(os.environ.get('ANCHOR_LAMBDA', '0.0'))  # L2 reg toward baseline weights
    save_dir_rel = os.environ.get('SAVE_DIR', 'data/outputs/btcv_fm_pl_finetune_k8_lr1e5')

    save_dir = os.path.join(_THIS_DIR, save_dir_rel)
    os.makedirs(save_dir, exist_ok=True)
    log_path = os.path.join(save_dir, 'logs.jsonl')

    pseudo_path = os.path.join(_THIS_DIR, pseudo_rel)
    print(f'[*] Loading pseudo-labels from {pseudo_path}')
    with open(pseudo_path) as f:
        pl_data = json.load(f)

    # Build idx → pseudo-label lookup, optionally filtering by gain quality
    def _gain(s):
        return float(s.get('best_iou', 0)) - float(s.get('det_iou', 0))

    pseudo_labels_map = {
        s['idx']: s for s in pl_data['samples']
        if 'error' not in s and _gain(s) >= gain_threshold
    }
    print(f'[*] Loaded {len(pseudo_labels_map)} pseudo-labels (k={pl_data["meta"]["k"]}, '
          f'gain_threshold={gain_threshold})')
    print(f'    mean_gain={pl_data["meta"].get("mean_gain", "?"):+}  '
          f'median_best={pl_data["meta"].get("median_best", "?")}')

    ckpt_path = os.path.join(_THIS_DIR, ckpt_rel)
    model, device = load_model(ckpt_path)

    # Only train the denoiser; freeze CNN backbone
    trainable = []
    for name, p in model.named_parameters():
        if 'gcn' in name and ('denoiser' in name or 'flow' in name or 'diffusion' in name):
            p.requires_grad_(True)
            trainable.append(p)
        else:
            p.requires_grad_(False)
    # Fallback: if no denoiser found, train gcn only
    if not trainable:
        print('[!] No denoiser params found; training full gcn')
        for name, p in model.named_parameters():
            if 'gcn' in name:
                p.requires_grad_(True)
                trainable.append(p)
            else:
                p.requires_grad_(False)

    print(f'[*] Trainable params: {sum(p.numel() for p in trainable):,}')
    optimizer = torch.optim.Adam(trainable, lr=lr)

    # Anchor weights for L2 regularization — keeps model close to baseline
    anchor_weights = None
    if anchor_lambda > 0:
        anchor_weights = {
            name: p.detach().clone()
            for name, p in model.named_parameters()
            if p.requires_grad
        }
        print(f'[*] Anchor regularization: lambda={anchor_lambda}')

    # Load dataset (supports 'train' or 'test' split via SPLIT env var)
    split = os.environ.get('SPLIT', 'train')
    if split == 'test':
        dataset = make_dataset(cfg, cfg.test.dataset, make_transforms(cfg, False), False)
    else:
        dataset = make_dataset(cfg, cfg.train.dataset, make_transforms(cfg, True), True)
    collator = make_collator(cfg)
    available_idxs = sorted(pseudo_labels_map.keys())
    n_avail = len(available_idxs)
    print(f'[*] Training on {n_avail} samples  lr={lr}  steps={steps}  iter_steps={iter_steps}')

    step = 0
    losses = []

    while step < steps:
        # Sample a mini-batch (random shuffle of available idxs)
        random.shuffle(available_idxs)
        batch_idxs = available_idxs[:batch_size]

        # Process each sample individually (they may have different n_contours)
        batch_loss, batch_count = 0.0, 0
        for sample_idx in batch_idxs:
            pl_entry = pseudo_labels_map[sample_idx]
            b = collator([dataset[sample_idx]])
            loss_val, gnorm = finetune_step(
                model, device, b, pl_entry, optimizer, grad_clip,
                iter_steps=iter_steps,
                anchor_weights=anchor_weights,
                anchor_lambda=anchor_lambda,
            )
            if loss_val is not None:
                batch_loss += loss_val
                batch_count += 1

        if batch_count == 0:
            continue

        step += 1
        mean_loss = batch_loss / batch_count
        losses.append(mean_loss)

        log_item = {
            'step': step,
            'loss': mean_loss,
            'timestamp': datetime.datetime.now().isoformat(),
        }
        with open(log_path, 'a') as f:
            f.write(json.dumps(log_item) + '\n')

        if step % 10 == 0 or step <= 5:
            print(f'[step {step:4d}/{steps}] loss={mean_loss:.6f}  '
                  f'loss_avg50={np.mean(losses[-50:]):.6f}')

        if step % save_every == 0:
            ckpt_saved = save_checkpoint(model, step, save_dir)
            print(f'[✔] Saved {ckpt_saved}')

    # Final save
    if step % save_every != 0:
        ckpt_saved = save_checkpoint(model, step, save_dir)
        print(f'[✔] Final checkpoint: {ckpt_saved}')

    print(f'\n[*] Fine-tuning done. {step} steps, final_loss={losses[-1]:.6f}')
    print(f'    Checkpoints in {save_dir}/checkpoints/')


if __name__ == '__main__':
    main()
